version: 35
jobs:
- name: Build and Publish Docker Image
  jobExecutor: SudoDocker
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: node:latest
    interpreter: !DefaultInterpreter
      commands: "mkdir dist\nnpm install \nnpm run build\n"
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build and publish docker image
    output: !RegistryOutput
      tags: sudo-ha-dashboard/sudo-ha-dashboard:latest
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
